# Use the Google-Built OpenTelemetry Collector image
FROM gcr.io/cloud-operations-collection/google-cloud-ops-otel-collector:latest

# The Google-Built image expects the config in /etc/otelcol/
COPY otel-config.yaml /etc/otelcol/config.yaml
