output "instavibe_app_cloud_run_service_url" {
  description = "The URL of the deployed Instavibe application Cloud Run service."
  # Value will only be known if the service is deployed (i.e., var.orchestrator_agent_deployed_and_var_updated is true)
  # Accessing google_cloud_run_v2_service.instavibe_app[0] because count is used.
  value       = var.orchestrator_agent_deployed_and_var_updated && length(google_cloud_run_v2_service.instavibe_app) > 0 ? google_cloud_run_v2_service.instavibe_app[0].uri : "Instavibe App not deployed due to orchestrator_agent_deployed_and_var_updated being false or deployment error."
  sensitive   = false # URL is generally not sensitive
}

output "instavibe_app_cloud_run_service_name" {
  description = "The name of the deployed Instavibe application Cloud Run service."
  value       = var.orchestrator_agent_deployed_and_var_updated && length(google_cloud_run_v2_service.instavibe_app) > 0 ? google_cloud_run_v2_service.instavibe_app[0].name : "Instavibe App not deployed."
}

output "instavibe_app_service_account_email" {
  description = "The email address of the service account used by the Instavibe application."
  value       = google_service_account.instavibe_app_sa.email
}

output "spanner_instance_name" {
  description = "The name of the Spanner instance."
  value       = google_spanner_instance.main.name
}

output "spanner_database_name" {
  description = "The name of the Spanner database."
  value       = google_spanner_database.main.name
}

# --- Agent Resource Name Outputs (for verification) ---
# These reflect the input variables, useful for confirming what Terraform used.
# The actual resource names are generated by Python scripts and manually fed back.
# These outputs help verify the values Terraform is currently using for them.

output "configured_planner_agent_resource_name" {
  description = "The configured Planner agent resource name (as provided in variables)."
  value       = var.planner_agent_resource_name
}

output "configured_social_agent_resource_name" {
  description = "The configured Social agent resource name (as provided in variables)."
  value       = var.social_agent_resource_name
}

output "configured_platform_mcp_client_agent_resource_name" {
  description = "The configured Platform MCP Client agent resource name (as provided in variables)."
  value       = var.platform_mcp_client_agent_resource_name
}

output "configured_orchestrate_agent_resource_name" {
  description = "The configured Orchestrate agent resource name (as provided in variables)."
  value       = var.orchestrate_agent_resource_name
}

output "vertex_ai_staging_bucket_configuration" {
  description = "The configured Vertex AI staging bucket name."
  value       = var.vertex_ai_staging_bucket
}

# --- Phased Deployment Control Flag Status ---
output "tool_agents_deployment_phase_status" {
  description = "Status of the 'tool_agents_deployed_and_vars_updated' flag. If true, Terraform expects tool agent resource names to be populated."
  value       = var.tool_agents_deployed_and_vars_updated
}

output "orchestrator_agent_deployment_phase_status" {
  description = "Status of the 'orchestrator_agent_deployed_and_var_updated' flag. If true, Terraform expects orchestrator agent resource name to be populated for app deployment."
  value       = var.orchestrator_agent_deployed_and_var_updated
}
