"""
Orchestrate Agent - Cloud Run A2A Server

Exposes the Orchestrate Agent via standard A2A protocol.
The AgentCard is auto-generated by to_a2a() with correct defaults.
"""

import os
import logging
from google.adk.a2a.utils.agent_to_a2a import to_a2a
from agents.orchestrate.agent import root_agent
from fastapi import FastAPI, Body
from fastapi.responses import StreamingResponse
from google.adk.agents import InvocationContext
from google.genai.types import Content, Part
import json

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)

# Get service URL from Cloud Run environment
service_name = os.getenv("K_SERVICE", "orchestrate-agent")
region = os.getenv("CLOUD_RUN_REGION", "us-central1")
project_id = os.getenv("GOOGLE_CLOUD_PROJECT", "laah-genai")

# Construct the Cloud Run URL
service_url = os.getenv(
    "SERVICE_URL",
    f"https://{service_name}-placeholder.{region}.run.app"
)

logger.info(f"🚀 Initializing Orchestrate Agent A2A Server")
logger.info(f"   Service URL: {service_url}")
logger.info(f"   Project: {project_id}")
logger.info(f"   Region: {region}")

# Parse host from service_url for card generation
from urllib.parse import urlparse
parsed = urlparse(service_url)
host = parsed.netloc
port = 443 if parsed.scheme == "https" else 80

# Create the main FastAPI app
app = FastAPI()

# Create the A2A application
a2a_app = to_a2a(
    root_agent,
    host=host,
    port=port,
    protocol=parsed.scheme
)

# Mount the A2A app
app.mount("/a2a", a2a_app)

logger.info(f"   Agent Card URL: {service_url}/a2a/.well-known/agent.json")

# --- CUSTOM HTTP ENDPOINT FOR DIRECT ACCESS ---
from google.adk.runners import Runner
from google.adk.sessions import InMemorySessionService
import uuid

# Create a shared session service and runner for the /chat endpoint
_session_service = InMemorySessionService()
_runner = Runner(
    agent=root_agent,
    app_name="orchestrate",
    session_service=_session_service
)

@app.post("/chat")
async def chat_endpoint(payload: dict = Body(...)):
    """
    Direct HTTP endpoint for chatting with the agent.
    Accepts JSON: {"prompt": "user message"}
    Returns: Streaming text response
    """
    prompt = payload.get("prompt")
    if not prompt:
        return {"error": "Missing 'prompt' in body"}

    logger.info(f"📨 Received /chat request: {prompt[:50]}...")

    # Generate a unique user/session for this request (stateless)
    user_id = f"chat-user-{uuid.uuid4().hex[:8]}"
    session_id = f"chat-session-{uuid.uuid4().hex[:8]}"
    
    # Create the session first - Runner.run_async requires an existing session
    await _session_service.create_session(
        app_name="orchestrate",
        user_id=user_id,
        session_id=session_id
    )

    async def response_generator():
        event_count = 0
        try:
            # Use the Runner to execute the agent with proper context
            async for event in _runner.run_async(
                user_id=user_id,
                session_id=session_id,
                new_message=Content(parts=[Part(text=prompt)])
            ):
                event_count += 1
                logger.info(f"📦 Event #{event_count}: type={type(event).__name__}, author={getattr(event, 'author', 'N/A')}")
                
                # Log event details for debugging
                if hasattr(event, 'content') and event.content:
                    logger.info(f"   Content: {event.content}")
                    if hasattr(event.content, 'parts') and event.content.parts:
                        for i, part in enumerate(event.content.parts):
                            text = getattr(part, 'text', None)
                            logger.info(f"   Part[{i}]: {text[:100] if text else 'NO TEXT'}...")
                            if text:
                                yield text
                else:
                    logger.info(f"   No content in event")
                    
            logger.info(f"📊 Total events received: {event_count}")
            
        except Exception as e:
            logger.error(f"Error in /chat stream: {e}", exc_info=True)
            yield f"\n[Error: {str(e)}]"

    return StreamingResponse(response_generator(), media_type="text/plain")

if __name__ == "__main__":
    import uvicorn
    
    port = int(os.getenv("PORT", "8080"))
    logger.info(f"🌐 Starting Orchestrate Agent server on port {port}")
    
    uvicorn.run(
        app,
        host="0.0.0.0",
        port=port,
        log_level="info",
        access_log=True
    )
